
app:
  id: uaa-service
apollo:
  bootstrap:
    enabled: true
    #    eagerLoad:
    #      enabled: true
    namespaces: application,micro_service.spring-boot-druid,micro_service.spring-boot-http,micro_service.spring-eureka,micro_service.spring-hystrix,micro_service.spring-cloud-feign,micro_service.spring-ribbon

spring:
  application:
    name: uaa-service

  main:
    allow-bean-definition-overriding: true

logging:
  config: classpath:log4j2-dev.xml




