# -Denv=dev -Dapollo.cluster=DEFAULT -Dserver.port=53010
app:
  id: gateway-server
apollo:
  bootstrap:
    enabled: true
    namespaces: application,micro_service.spring-boot-http,micro_service.spring-eureka,micro_service.spring-hystrix,micro_service.spring-ribbon,micro_service.spring-boot-redis

spring:
  application:
    name: gateway-server

logging:
  config: classpath:log4j2-dev.xml




